version: "3.8"
services:
  myurjc-app:
    container_name: myurjc
    image: jesussmariscal/reurjc
    ports:
      - "8443:8443"
      - "8080:8080"
    depends_on:
      - myurjc-DB
      - moodle-app
      - attendance-service 
    command: ["/bin/sh", "-c", "until curl -sSf http://moodle-app > /dev/null; do echo 'Waiting for Moodle...'; sleep 5; done; java -jar /app/app.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://myurjc-DB:3306/tfgdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - RUNNING_IN_DOCKER=true
      - MOODLE_HOST=moodle-app
      - MOODLE_PORT=80
      - MOODLE_DB_HOST=moodle-db
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodleuser
      - MOODLE_DB_PASSWORD=moodlepass
      - ATTENDANCE_SERVICE_URL=http://attendance-service:8081 
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
      - ../../Backend/src/main/resources/firebase-service-account.json:/app/firebase-service-account.json 
      - ../../Backend/src/main/resources/keystore.p12:/app/certs/keystore.p12 

  myurjc-DB:
    container_name: myurjc-DB
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=tfgdb
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mis_datos_mysql:/var/lib/mysql

  moodle-app:
    container_name: moodle
    image: jesussmariscal/mymoodle:latest
    ports:
      - "80:80"
    depends_on:
      - moodle-db
    environment:
      - MOODLE_DB_TYPE=mysqli
      - MOODLE_DB_HOST=moodle-db
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=moodleuser
      - MOODLE_DB_PASSWORD=moodlepass
      - MOODLE_WWWROOT=http://localhost
    volumes:
      - moodle_data:/var/www/html/moodledata

  moodle-db:
    container_name: moodle-db
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=moodle
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=moodleuser
      - MYSQL_PASSWORD=moodlepass
    volumes:
      - moodle_db_data:/var/lib/mysql

  attendance-service:
    container_name: attendance
    image: jesussmariscal/attendance
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://attendance-db:3306/attendancedb
      - SPRING_DATASOURCE_USERNAME=root  
      - SPRING_DATASOURCE_PASSWORD=password 
    depends_on:
      - attendance-db  

  attendance-db: 
    container_name: attendance-db
    image: mysql:8.3.0  
    environment:
      - MYSQL_DATABASE=attendancedb 
      - MYSQL_ROOT_PASSWORD=password  
    volumes:
      - attendance_db_data:/var/lib/mysql  

  notifications-service:
    container_name: notifications
    image: jesussmariscal/notifications
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://notifications-db:3306/attendances
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - MICROSERVICE_PRINCIPAL_URL=http://myurjc-app:8080
    depends_on:
      - notifications-db
      - myurjc-app

  notifications-db:
    container_name: notifications-db
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=attendances
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - notifications_db_data:/var/lib/mysql

volumes:
  mis_datos_mysql:
  moodle_data:
  moodle_db_data:
  attendance_db_data:
  notifications_db_data: