spring.application.name=Asistance

# Database Configuration
spring.datasource.url=jdbc:mysql://attendance-db:3306/attendances
spring.datasource.username=root
spring.datasource.password=password

# Spring JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jackson.time-zone=Europe/Madrid
server.port=8081