apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-db
  template:
    metadata:
      labels:
        app: attendance-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.3.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "attendancedb"
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: attendance-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-db-service
spec:
  selector:
    app: attendance-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attendance-db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi