apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-service
  template:
    metadata:
      labels:
        app: attendance-service
    spec:
      containers:
      - name: attendance
        image: gcr.io/tfgurjc-e9e62/attendance:latest
        ports:
        - containerPort: 8081
        env:
        - name: SERVER_PORT
          value: "8081"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://attendance-db-service:3306/attendancedb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service-service
spec:
  selector:
    app: attendance-service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP