apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle-db
  template:
    metadata:
      labels:
        app: moodle-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.3.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "moodle"
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        - name: MYSQL_USER
          value: "moodleuser"
        - name: MYSQL_PASSWORD
          value: "moodlepass"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: moodle-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: moodle-db-service
spec:
  selector:
    app: moodle-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi