name: CI/CD Backend

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.31
        env:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: tfgdb
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        env:
          DB_DATABASE: tfgdb
          DB_USER: root
          DB_PASSWORD: 12345678
        run: |
          cd ./Backend
          mvn clean install -DskipTests
          mvn test -Dspring.profiles.active=test

      - name: Show MySQL logs
        if: failure()
        run: |
          docker logs ${{ job.services.mysql.id }}

      - name: Dockerize application
        env:
          DB_DATABASE: tfgdb
          DB_USER: root
          DB_PASSWORD: 12345678
        run: |
          docker build -t jesussmariscal/reurjc -f ./Docker/App/Dockerfile .
          cd ./Docker/App
          docker-compose -p myurjc up -d

      - name: Stop Docker Compose
        if: always()
        run: |
          cd ./Docker/App
          docker-compose -p myurjc down